[bind]
socket = "[::]:1920"

[weather]
latitude = 48.5227
longitude = 9.0522
daily = ["precipitation_sum", "temperature_2m_max", "temperature_2m_min", "wind_speed_10m_max"]
hourly = ["temperature_2m", "rain", "precipitation", "wind_speed_10m"]
models = "icon_seamless"
current = ["temperature_2m", "is_day", "precipitation", "wind_speed_10m"]
timezone = "Europe/Berlin"