[bind]
socket = "[::]:1920"

[weather]
latitude = 48.5227
longitude = 9.0522
models = ["icon_seamless"]
timezone = "Europe/Berlin"

[[departure]]
point = "de:08416:10103"

[departure.show_next]
secs = 0
nanos = 0
