[package]
name = "stopfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }

log = "0.4.28"
env_logger = "0.11.8"

nestify = { version = "0.3.3" }

reqwest = { version = "0.12.24", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }